### PR TITLE
Default Oracle VARCHAR2 to CHAR 255 length

### PR DESCRIPTION
**Pull request by gracecodes144**
Also, improve AWS deployment.

### CODE REVIEW

**Comment by gracecodes144** [comment]
@parthdivekar Can you take a look at this update for the new VARCHAR2 defaults? http://dmsa-df1ad3d8.elasticbeanstalk.com/ Thanks!

**Comment by parthdivekar** [comment]
The table creation scripts for Oracle works. Here are the errors.

ALTER TABLE condition ADD CONSTRAINT xpk_condition PRIMARY KEY (conditionid)
Error at line 286
ORA-02260: table can have only one primary key

ALTER TABLE death ADD CONSTRAINT xpk_death PRIMARY KEY (patid, death_date, death_source)
Error at line 292
ORA-02260: table can have only one primary key

ALTER TABLE death_cause ADD CONSTRAINT xpk_death_cause PRIMARY KEY (patid, death_cause, death_cause_code, death_cause_type, death_cause_source)
Error at line 298
ORA-02260: table can have only one primary key

ALTER TABLE demographic ADD CONSTRAINT xpk_demographic PRIMARY KEY (patid)
Error at line 300
ORA-02260: table can have only one primary key

ALTER TABLE diagnosis ADD CONSTRAINT xpk_diagnosis PRIMARY KEY (diagnosisid)
Error at line 304
ORA-02260: table can have only one primary key

ALTER TABLE dispensing ADD CONSTRAINT xpk_dispensing PRIMARY KEY (dispensingid)
Error at line 308
ORA-02260: table can have only one primary key

ALTER TABLE encounter ADD CONSTRAINT xpk_encounter PRIMARY KEY (encounterid)
Error at line 314
ORA-02260: table can have only one primary key

ALTER TABLE enrollment ADD CONSTRAINT xpk_enrollment PRIMARY KEY (patid, enr_start_date, enr_basis)
Error at line 318
ORA-02260: table can have only one primary key

ALTER TABLE harvest ADD CONSTRAINT xpk_harvest PRIMARY KEY (networkid, datamartid)
Error at line 322
ORA-02260: table can have only one primary key

ALTER TABLE lab_result_cm ADD CONSTRAINT xpk_lab_result_cm PRIMARY KEY (lab_result_cm_id)
Error at line 324
ORA-02260: table can have only one primary key

ALTER TABLE pcornet_trial ADD CONSTRAINT xpk_pcornet_trial PRIMARY KEY (patid, trialid, participantid)
Error at line 332
ORA-02260: table can have only one primary key

ALTER TABLE prescribing ADD CONSTRAINT xpk_prescribing PRIMARY KEY (prescribingid)
Error at line 334
ORA-02260: table can have only one primary key

ALTER TABLE pro_cm ADD CONSTRAINT xpk_pro_cm PRIMARY KEY (pro_cm_id)
Error at line 342
ORA-02260: table can have only one primary key

ALTER TABLE procedures ADD CONSTRAINT xpk_procedures PRIMARY KEY (proceduresid)
Error at line 346
ORA-02260: table can have only one primary key

ALTER TABLE vital ADD CONSTRAINT xpk_vital PRIMARY KEY (vitalid)
Error at line 352
ORA-02260: table can have only one primary key

Either remove “CONSTRAINT” clause from table definition or remove Alter Table Statement that recreates Primary Key.

One more suggestion :

If you can add

Set define off

Spool <filename>.log

And at the end

Spool off

This will help capture any errors in the file.

Hope this helps.

Parth

**Comment by gracecodes144** [comment]
Thoughts:

I would prefer not to include the primary key in the table definition and instead have them in the constraints section to allow maximum flexibility in data loading (by defining the tables, loading the data, and only then adding primary keys). On the other hand, its probably "good practice" to only load data that satisfies the primary keys (or alternately, only have primary keys that the data will satisfy). Ultimately, this is decided by the fact that I can't figure out how to remove the primary key from the table definition, but I can definitely remove from the constraints section, so that's what I'm doing.

I am not going to add the logging statements you suggest because I imagine different users will want the flexibility to log in different ways. For example, when I start using this DDL in our automated data loading package, I'm going to wrap the code in custom logging functions. Basically, I think it is out of scope for this package, which only aims to generate the DDL and then let consumers do with it as they wish.

**Comment by gracecodes144** [comment]
@parthdivekar check this: http://dmsa-424079e6.elasticbeanstalk.com/pcornet/v3/ddl/oracle/

**Comment by parthdivekar** [comment]
Aaron

Seems like you did Search and Replace for all Varchars and set the size to 4000. I wrote previously that do it if only you are not using it for Indexing. (Raw Source fields typically).
If you have a key field set for 4000 and using it in composite index then the index creation would fail.

If you don’t mind, can I fix it and send it to you by Monday?

Parth

**Comment by gracecodes144** [comment]
The DDL is being auto-generated from the information in the chop-dbhi/data-models repository, so I didn't manually edit it at all. What I did was add a rule that sets string fields without a defined length to 4000.

Unfortunately, the PCORnet CDM V3 does not define lengths for a large variety of fields, including both raw and non-raw fields.

This may mean that we should be setting some of the lengths in the standard data model definition. If you send me a file with what you think is the right lengths, I can add them there.

**Comment by parthdivekar** [comment]
I will send you how we have set it up by EoD Monday.

**Comment by gracecodes144** [comment]
@parthdivekar Any progress on the suggested VARCHAR lengths for indexed fields?

**Comment by parthdivekar** [comment]
Just sent via email.
Please take a look at it and let me know if you have any questions.
Parth

**Comment by gracecodes144** [comment]
Via email conversation, @parthdivekar has agreed that a default value of 255 is acceptable and I am going to adopt this convention as an attempt to balance:
- Not modifying the released PCORnet spec in our definitions (and retaining the intended flexibility of that spec)
- Keeping the DDL generation relatively transparent and simple
- Accommodating longer raw data source values without effecting the ability to index id fields

**Comment by gracecodes144** [comment]
The checks failed because AWS deploy failed because I'm at my elastic IP limit...yet another corner case to navigate. I am going to merge anyway and fix the deployment issue in another branch.

**Pull request merged**
